name: Build EXE and Commit to Branch

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-course-exe:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m playwright install
        pip install pyinstaller

    - name: Build EXE
      run: |
        pyinstaller --onefile main.py
        mkdir output
        move dist\\main.exe output\\course_automation.exe

    - name: Commit EXE to output branch
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git fetch
        git switch -c build-output || git switch build-output
        copy output\\course_automation.exe .
        git add course_automation.exe
        git commit -m "Add latest EXE build"
        git push -f origin build-output
