name: Build EXE for Course Automation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-course-exe:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m playwright install

    - name: Build EXE with PyInstaller
      run: |
        pip install pyinstaller
        pyinstaller --onefile main.py

    - name: Upload Course Automation EXE
      uses: actions/upload-artifact@v3
      with:
        name: course-automation-exe-renamed
        path: dist/*.exe
